//EECS 384 Assignment 3
//Description: Recieves emails and uses a max heap to proritizes, keep count, delete read emails, 
//             and print the email information based on user commands.
//Intputs: File containing email parameters and commands
//Outputs: terminal output following the commands
//Collaborators: None
//Other sources: ChatGPT and Gemini
//Author’s full name: Mikayla Pelletier
//Creation date: 10/1/2026
//Revision date: 10/1/2026
//Revisions: Added code generated by AI and improved correctness, excecution time, space complexity, and maintainability


// Include the iostream library so the program can read input
// from standard input and display output to the user.
#include <iostream>

// Include the string library so the program can store and
// manipulate strings such as sender names, subjects, and dates.
#include <string>

// Include the sstream library so the program can separate
// and extract values from strings.
#include <sstream>

// Include the vector library so the MaxHeap can use a
// dynamically sized array to store Email objects.
#include <vector>

// Include the cctype library so the program can use
// character-checking functions such as std::isdigit().
#include <cctype>


// ------------------------------------------------------------
// Email structure (Coded by Gemini)
// ------------------------------------------------------------
// This structure represents one email.
//
// Each Email stores the original information that needs to
// be displayed as well as precomputed information needed
// to compare emails efficiently.
//
// The category priority and date values are calculated once
// when the Email is created. This prevents the program from
// repeatedly converting strings during heap comparisons.
struct Email
{
    // Store the sender category, such as "Boss", "Peer",
    // "Subordinate", "ImportantPerson", or "OtherPerson".
    std::string senderCategory;

    // Store the subject line of the email.
    std::string subject;

    // Store the original date string exactly as entered
    // after unnecessary surrounding spaces have been removed.
    std::string dateStr;

    // Store the numerical priority of the sender category.
    // A larger number means a higher sender priority.
    int categoryPriority;

    // Store the year portion of the date.
    int year;

    // Store the month portion of the date.
    int month;

    // Store the day portion of the date.
    int day;


    // --------------------------------------------------------
    // Email constructor (Coded by Gemini)
    // --------------------------------------------------------
    // This constructor creates and initializes an Email object.
    //
    // It receives the sender category, subject, and date,
    // calculates the sender priority, and parses the date.
    Email(const std::string& category,
          const std::string& emailSubject,
          const std::string& date)
        // Store the sender category.
        : senderCategory(category),

          // Store the email subject.
          subject(emailSubject),

          // Store the original date string.
          dateStr(date),

          // Calculate and store the sender category priority.
          categoryPriority(getCategoryPriority(category)),

          // Initialize the date values before parsing.
          year(0),
          month(0),
          day(0)
    {
        // Convert the date string into separate month, day,
        // and year integer values.
        parseDate(date);
    }


    // --------------------------------------------------------
    // Get category priority (Coded by Gemini)
    // --------------------------------------------------------
    // This function converts a sender category into a numerical
    // priority.
    //
    // Higher numbers represent higher priority.
    static int getCategoryPriority(const std::string& category)
    {
        // Boss has the highest priority.
        if (category == "Boss")
        {
            return 5;
        }

        // Subordinate has the second-highest priority.
        if (category == "Subordinate")
        {
            return 4;
        }

        // Peer has the third-highest priority.
        if (category == "Peer")
        {
            return 3;
        }

        // ImportantPerson has the fourth-highest priority.
        if (category == "ImportantPerson")
        {
            return 2;
        }

        // Any other category receives the lowest priority.
        return 1;
    }


    // --------------------------------------------------------
    // Parse date (Coded by Gemini)
    // --------------------------------------------------------
    // This function takes a date in MM-DD-YYYY format and
    // separates it into month, day, and year values.
    void parseDate(const std::string& date)
    {
        // Create a string stream containing the date.
        std::stringstream dateStream(date);

        // Store the dash characters between the date fields.
        char firstDash;
        char secondDash;

        // Extract the month, first dash, day, second dash,
        // and year from the date string.
        dateStream >> month
                   >> firstDash
                   >> day
                   >> secondDash
                   >> year;
    }


    // --------------------------------------------------------
    // Check whether a year is a leap year (Coded by Gemini)
    // --------------------------------------------------------
    // A leap year has 366 days instead of 365.
    //
    // A year is a leap year when:
    // - It is divisible by 400, OR
    // - It is divisible by 4 but not by 100.
    static bool isLeapYear(int checkYear)
    {
        // Check whether the year is evenly divisible by 400.
        if (checkYear % 400 == 0)
        {
            // Years divisible by 400 are leap years.
            return true;
        }

        // Check whether the year is divisible by 100.
        if (checkYear % 100 == 0)
        {
            // Years divisible by 100 but not 400 are not leap years.
            return false;
        }

        // Check whether the year is divisible by 4.
        return checkYear % 4 == 0;
    }


    // --------------------------------------------------------
    // Validate date (Coded by Gemini)
    // --------------------------------------------------------
    // This function checks whether a date is a valid date in
    // MM-DD-YYYY format.
    //
    // It checks:
    // 1. The string has exactly 10 characters.
    // 2. Positions 3 and 6 contain '-'.
    // 3. All other positions contain digits.
    // 4. The month is between 1 and 12.
    // 5. The day is valid for the specified month.
    // 6. February correctly handles leap years.
    static bool isValidDate(const std::string& date)
    {
        // A properly formatted MM-DD-YYYY date contains
        // exactly 10 characters.
        if (date.length() != 10)
        {
            // The date does not have the required length.
            return false;
        }

        // Check that the first separator is a dash.
        if (date[2] != '-')
        {
            // The first separator is incorrect.
            return false;
        }

        // Check that the second separator is a dash.
        if (date[5] != '-')
        {
            // The second separator is incorrect.
            return false;
        }


        // Check the month digits.
        if (!std::isdigit(static_cast<unsigned char>(date[0])) ||
            !std::isdigit(static_cast<unsigned char>(date[1])))
        {
            // The month contains a non-digit character.
            return false;
        }


        // Check the day digits.
        if (!std::isdigit(static_cast<unsigned char>(date[3])) ||
            !std::isdigit(static_cast<unsigned char>(date[4])))
        {
            // The day contains a non-digit character.
            return false;
        }


        // Check all four year digits.
        if (!std::isdigit(static_cast<unsigned char>(date[6])) ||
            !std::isdigit(static_cast<unsigned char>(date[7])) ||
            !std::isdigit(static_cast<unsigned char>(date[8])) ||
            !std::isdigit(static_cast<unsigned char>(date[9])))
        {
            // The year contains a non-digit character.
            return false;
        }


        // Convert the first two characters into the month number.
        int checkMonth =
            (date[0] - '0') * 10 +
            (date[1] - '0');

        // Convert the middle two characters into the day number.
        int checkDay =
            (date[3] - '0') * 10 +
            (date[4] - '0');

        // Convert the final four characters into the year number.
        int checkYear =
            (date[6] - '0') * 1000 +
            (date[7] - '0') * 100 +
            (date[8] - '0') * 10 +
            (date[9] - '0');


        // A month must be between January and December.
        if (checkMonth < 1 || checkMonth > 12)
        {
            // The month is invalid.
            return false;
        }


        // Store the maximum number of days for the selected month.
        int maximumDays;


        // February is handled separately because its length
        // depends on whether the year is a leap year.
        if (checkMonth == 2)
        {
            // February has 29 days during a leap year.
            if (isLeapYear(checkYear))
            {
                maximumDays = 29;
            }
            else
            {
                // February has 28 days during a non-leap year.
                maximumDays = 28;
            }
        }

        // April, June, September, and November have 30 days.
        else if (checkMonth == 4 ||
                 checkMonth == 6 ||
                 checkMonth == 9 ||
                 checkMonth == 11)
        {
            maximumDays = 30;
        }

        // Every remaining valid month has 31 days.
        else
        {
            maximumDays = 31;
        }


        // Check whether the day is within the valid range.
        if (checkDay < 1 || checkDay > maximumDays)
        {
            // The day is invalid for the selected month.
            return false;
        }


        // All validation checks passed, so the date is valid.
        return true;
    }


    // --------------------------------------------------------
    // Compare email priority (Coded by Gemini)
    // --------------------------------------------------------
    // This function returns true when the current Email has
    // a higher priority than the other Email.
    //
    // Priority is determined using:
    // 1. Sender category.
    // 2. Newest year.
    // 3. Newest month.
    // 4. Newest day.
    bool hasHigherPriorityThan(const Email& other) const
    {
        // Compare sender category priorities first.
        if (categoryPriority != other.categoryPriority)
        {
            // The larger category priority is higher priority.
            return categoryPriority > other.categoryPriority;
        }

        // If categories are equal, compare years.
        if (year != other.year)
        {
            // The larger year represents a newer email.
            return year > other.year;
        }

        // If the years are equal, compare months.
        if (month != other.month)
        {
            // The larger month represents a newer email.
            return month > other.month;
        }

        // If the years and months are equal, compare days.
        // The larger day represents a newer email.
        return day > other.day;
    }
};


// ------------------------------------------------------------
// MaxHeap class (Coded by Gemini)
// ------------------------------------------------------------
// This class implements a max heap using a vector.
//
// The highest-priority email is always stored at index 0.
//
// The heap provides:
// - O(log n) insertion
// - O(1) access to the highest-priority email
// - O(log n) removal of the highest-priority email
// - O(1) size checking
class MaxHeap
{
private:

    // Store all Email objects in a dynamic vector.
    std::vector<Email> heap;


    // --------------------------------------------------------
    // Heapify Up (Coded by Gemini)
    // --------------------------------------------------------
    // This function moves an email upward after insertion
    // until the max-heap property is restored.
    void heapifyUp(std::size_t index)
    {
        // Continue while the current email has a parent.
        while (index > 0)
        {
            // Calculate the parent's index in the heap.
            std::size_t parentIndex = (index - 1) / 2;

            // Check whether the current email has a higher
            // priority than its parent.
            if (heap[index].hasHigherPriorityThan(heap[parentIndex]))
            {
                // Swap the current email with its parent.
                std::swap(heap[index], heap[parentIndex]);

                // Continue checking from the parent's position.
                index = parentIndex;
            }
            else
            {
                // The heap property is already satisfied.
                break;
            }
        }
    }


    // --------------------------------------------------------
    // Heapify Down (Coded by Gemini)
    // --------------------------------------------------------
    // This function moves an email downward after the root
    // has been removed.
    void heapifyDown(std::size_t index)
    {
        // Store the current number of emails in the heap.
        std::size_t size = heap.size();

        // Continue until the heap property is restored.
        while (true)
        {
            // Assume the current node has the highest priority.
            std::size_t highestPriorityIndex = index;

            // Calculate the left child's index.
            std::size_t leftChild = 2 * index + 1;

            // Calculate the right child's index.
            std::size_t rightChild = 2 * index + 2;


            // Check whether the left child exists and has
            // a higher priority than the current node.
            if (leftChild < size &&
                heap[leftChild].hasHigherPriorityThan(
                    heap[highestPriorityIndex]))
            {
                // The left child becomes the highest-priority node.
                highestPriorityIndex = leftChild;
            }


            // Check whether the right child exists and has
            // a higher priority than the current highest-priority node.
            if (rightChild < size &&
                heap[rightChild].hasHigherPriorityThan(
                    heap[highestPriorityIndex]))
            {
                // The right child becomes the highest-priority node.
                highestPriorityIndex = rightChild;
            }


            // If the current node is still the highest-priority node,
            // the heap property has been restored.
            if (highestPriorityIndex == index)
            {
                // Stop moving downward.
                break;
            }


            // Swap the current node with the highest-priority child.
            std::swap(heap[index], heap[highestPriorityIndex]);

            // Continue heapifying from the child's previous position.
            index = highestPriorityIndex;
        }
    }


public:

    // --------------------------------------------------------
    // Insert (Coded by Gemini)
    // --------------------------------------------------------
    // Add an email to the heap.
    void insert(const Email& email)
    {
        // Add the new email to the end of the vector.
        heap.push_back(email);

        // Restore the max-heap property by moving the new
        // email upward.
        heapifyUp(heap.size() - 1);
    }


    // --------------------------------------------------------
    // Get Maximum (Coded by Gemini)
    // --------------------------------------------------------
    // Return the highest-priority email.
    //
    // A constant reference is returned so the Email object
    // does not have to be copied.
    const Email& getMax() const
    {
        // The highest-priority email is always at index 0.
        return heap.front();
    }


    // --------------------------------------------------------
    // Remove Maximum (Coded by Gemini)
    // --------------------------------------------------------
    // Remove the highest-priority email from the heap.
    void removeMax()
    {
        // Check whether the heap is empty.
        if (heap.empty())
        {
            // There is nothing to remove.
            return;
        }


        // Move the last email into the root position.
        heap[0] = heap.back();

        // Remove the last element because it has been moved
        // to the root.
        heap.pop_back();


        // Check whether an email remains in the heap.
        if (!heap.empty())
        {
            // Restore the max-heap property.
            heapifyDown(0);
        }
    }


    // --------------------------------------------------------
    // Is Empty (Coded by Gemini)
    // --------------------------------------------------------
    // Determine whether the heap contains zero emails.
    bool isEmpty() const
    {
        // Return true when the vector contains no emails.
        return heap.empty();
    }


    // --------------------------------------------------------
    // Size (Coded by Gemini)
    // --------------------------------------------------------
    // Return the number of emails currently in the heap.
    std::size_t size() const
    {
        // Return the vector's number of elements.
        return heap.size();
    }
};


// ------------------------------------------------------------
// Trim function (Coded by Gemini)
// ------------------------------------------------------------
// Remove spaces and tabs from the beginning and end of a string.
//
// Example:
// "  Boss  " becomes "Boss".
std::string trim(const std::string& str)
{
    // Find the first character that is not a space or tab.
    std::size_t start = str.find_first_not_of(" \t");

    // If every character is a space or tab, return an empty string.
    if (start == std::string::npos)
    {
        return "";
    }

    // Find the last character that is not a space or tab.
    std::size_t end = str.find_last_not_of(" \t");

    // Return only the portion between the first and last
    // non-whitespace characters.
    return str.substr(start, end - start + 1);
}


// ------------------------------------------------------------
// Main function (Coded by Gemini)
// ------------------------------------------------------------
// The main function reads commands from standard input.
//
// Supported commands are:
// EMAIL - Add an email.
// COUNT - Display the number of unread emails.
// NEXT  - Display the highest-priority email.
// READ  - Remove the highest-priority email.
int main()
{
    // Create an empty MaxHeap to store the emails.
    MaxHeap emailQueue;

    // Store one complete input line at a time.
    std::string line;


    // Read input until the end of the input stream is reached.
    while (std::getline(std::cin, line))
    {
        // Ignore completely empty lines.
        if (line.empty())
        {
            continue;
        }


        // ----------------------------------------------------
        // EMAIL command (Coded by Gemini)
        // ----------------------------------------------------
        // Expected format:
        //
        // EMAIL <sender category>, <subject>, <MM-DD-YYYY>
        //
        // Example:
        //
        // EMAIL Boss, Meeting, 10-01-2026
        if (line.rfind("EMAIL ", 0) == 0)
        {
            // Remove "EMAIL " from the beginning of the line.
            std::string data = line.substr(6);

            // Create a string stream to separate the fields.
            std::stringstream stream(data);

            // Store the sender category.
            std::string category;

            // Store the email subject.
            std::string subject;

            // Store the date.
            std::string dateStr;


            // Read the category up to the first comma.
            if (!std::getline(stream, category, ','))
            {
                // Tell the user that the EMAIL command is invalid.
                std::cout << "Invalid EMAIL command."
                          << std::endl
                          << std::endl;

                // Skip the rest of this iteration.
                continue;
            }


            // Read the subject up to the second comma.
            if (!std::getline(stream, subject, ','))
            {
                // Tell the user that the EMAIL command is invalid.
                std::cout << "Invalid EMAIL command."
                          << std::endl
                          << std::endl;

                // Skip the rest of this iteration.
                continue;
            }


            // Read the date from the remainder of the line.
            if (!std::getline(stream, dateStr))
            {
                // Tell the user that the EMAIL command is invalid.
                std::cout << "Invalid EMAIL command."
                          << std::endl
                          << std::endl;

                // Skip the rest of this iteration.
                continue;
            }


            // Remove unnecessary spaces from the category.
            category = trim(category);

            // Remove unnecessary spaces from the subject.
            subject = trim(subject);

            // Remove unnecessary spaces from the date.
            dateStr = trim(dateStr);


            // Make sure the sender category is not empty.
            if (category.empty())
            {
                // Tell the user that the category is invalid.
                std::cout << "Invalid EMAIL command: "
                          << "sender category cannot be empty."
                          << std::endl
                          << std::endl;

                // Skip this invalid email.
                continue;
            }


            // Make sure the subject is not empty.
            if (subject.empty())
            {
                // Tell the user that the subject is invalid.
                std::cout << "Invalid EMAIL command: "
                          << "subject cannot be empty."
                          << std::endl
                          << std::endl;

                // Skip this invalid email.
                continue;
            }


            // Validate the date before creating the Email object.
            if (!Email::isValidDate(dateStr))
            {
                // Tell the user that the date is invalid.
                std::cout << "Invalid email date: "
                          << dateStr
                          << ". Expected MM-DD-YYYY."
                          << std::endl
                          << std::endl;

                // Do not add the invalid email to the heap.
                continue;
            }


            // Create the Email object.
            //
            // The constructor automatically calculates the
            // category priority and parses the date.
            Email email(category, subject, dateStr);


            // Add the valid email to the max heap.
            emailQueue.insert(email);
        }


        // ----------------------------------------------------
        // COUNT command (Coded by Gemini)
        // ----------------------------------------------------
        // Display the number of unread emails.
        else if (line == "COUNT")
        {
            // Display the current number of emails.
            std::cout << "There are "
                      << emailQueue.size()
                      << " emails to read."
                      << std::endl;

            // Print a blank line after the output.
            std::cout << std::endl;
        }


        // ----------------------------------------------------
        // NEXT command (Coded by Gemini)
        // ----------------------------------------------------
        // Display the highest-priority email without removing it.
        else if (line == "NEXT")
        {
            // Check whether there are any emails.
            if (emailQueue.isEmpty())
            {
                // Tell the user that there are no emails.
                std::cout << "There are no emails to read."
                          << std::endl
                          << std::endl;
            }
            else
            {
                // Get a constant reference to the highest-priority email.
                const Email& top = emailQueue.getMax();

                // Display the heading.
                std::cout << "Next email:"
                          << std::endl;

                // Display the sender category.
                std::cout << "\tSender: "
                          << top.senderCategory
                          << std::endl;

                // Display the subject.
                std::cout << "\tSubject: "
                          << top.subject
                          << std::endl;

                // Display the original date.
                std::cout << "\tDate: "
                          << top.dateStr
                          << std::endl;

                // Print a blank line after the email.
                std::cout << std::endl;
            }
        }


        // ----------------------------------------------------
        // READ command (Coded by Gemini)
        // ----------------------------------------------------
        // Remove the highest-priority email from the heap.
        else if (line == "READ")
        {
            // Check whether there are any emails.
            if (emailQueue.isEmpty())
            {
                // Tell the user that there are no emails to read.
                std::cout << "There are no emails to read."
                          << std::endl
                          << std::endl;
            }
            else
            {
                // Remove the highest-priority email.
                emailQueue.removeMax();
            }
        }


        // ----------------------------------------------------
        // Invalid command (Coded by Gemini)
        // ----------------------------------------------------
        // If the input does not match any recognized command,
        // tell the user that the command is not recognized.
        else
        {
            // Display an error message for the invalid command.
            std::cout << "Invalid command: "
                      << line
                      << std::endl
                      << std::endl;
        }
    }


    // Return 0 to indicate that the program ended successfully.
    return 0;
}
